---
- name: install Python3
  hosts: docker_server
  become: yes
  tasks:
    - name: install Python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: python3
        update_cache: yes
        state: present

- name: install Docker
  hosts: docker_server
  become: yes
  tasks:
    - name: install Docker
      yum:
        name: docker
        update_cache: yes
        state: present