---
- name: install java and net-tools
  hosts: nexus_server
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=true force_apt_get=yes cache_valid_time=3600
    - name: install java 8
      apt:
        name: openjdk-8-jre-headless
        update_cache: true
    - name: install net-tools
      apt:
        name: net-tools
        update_cache: true

- name: download and extract Nexus installer
  hosts: nexus_server
  tasks:
    - name: see if Nexus folder already exists in /opt/
      stat:
        path: /opt/nexus
      register: stat_result
    - name: download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
    - name: unpack Nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: find Nexus folder name
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug: msg={{find_result}}
    - debug: msg={{stat_result.stat.exists}}
    - name: rename Nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      # conditional ensures this task only happens if the folder does not exist
      when: not stat_result.stat.exists

- name: create Nexus user and give folder ownership
  hosts: nexus_server
  tasks:
    - name: create Nexus group
      group:
        name: nexus
        state: present
    - name: create Nexus user
      user:
        name: nexus
        group: nexus
    - name: make nexus user owner of Nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: make nexus user owner of Sonatype folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: configure Nexus to start as the nexus user
  hosts: nexus_server
  tasks:
    - name: set run_as_user nexus.rc file
      #blockinfile:
        #path: /opt/nexus/bin/nexus.rc
         # pipe char is yaml syntax for a multi-line string (similar to a here-string)
        #block: |
          #run_as_user="nexus"
      # similar to the 'blockinfile' module is a module called 'lineinfile'
      # 'lineinfile' is useful in single-line cases to verify something is set or replace something
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"