---
- name: install java and net-tools
  hosts: nexus_server
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=true force_apt_get=yes cache_valid_time=3600
    - name: install java 8
      apt:
        name: openjdk-8-jre-headless
        update_cache: true
    - name: install net-tools
      apt:
        name: net-tools
        update_cache: true

- name: download and extract Nexus installer
  hosts: nexus_server
  tasks:
    - name: download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
    - name: unpack Nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find Nexus folder name
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug: msg={{find_result}}
    - name: see if Nexus folder already exists in /opt/
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}
    # conditional ensures this task only happens if the folder does not exist
    - name: rename Nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists